class ListaPrueba {
  Map<String, dynamic> lista = {
    '#01': 'Bulbasaur',
    '#02': 'Ivysaur',
    '#03': 'Venusaur',
    '#04': 'Charmander',
    '#05': 'Charmeleon',
    '#06': 'Charizard',
    '#07': 'Squirtle',
    '#08': 'Wartortle',
    '#09': 'Blastoise',
    '#10': 'Caterpie',
    '#11': 'Metapod',
    '#12': 'Butterfree',
    '#13': 'Weedle',
    '#14': 'Kakuna',
    '#15': 'Beedrill',
    '#16': 'Pidgey',
    '#17': 'Pidgeotto',
    '#18': 'Pidgeot',
    '#19': 'Rattata',
    '#20': 'Ratticate',
    '#21': 'Spearow',
    '#22': 'Fearow',
    '#23': 'Ekans',
    '#24': 'Arbok',
    '#25': 'Pikachu',
    '#26': 'Raichu',
  };
}
